name: Sheep
main: KnownUnown\Sheep\Sheep
version: 5.0.0
api: 2.0.0

author: KnownUnown
description: A plugin for [installing, uninstalling, viewing] other plugins.
website: https://www.github.com/KnownUnown/Sheep

permissions:
  sheep.command.base:
    description: "Allows the user access to the base Sheep command, but not necessarily the subcommands."
    default: op


