name: Sheep
main: Sheep\Sheep
version: 5.0.0
api: [3.0.0-ALPHA4]

author: KnownUnown
description: A plugin for [installing, uninstalling, viewing] other plugins.
website: https://www.github.com/KnownUnown/Sheep

permissions:
  sheep.command:
    description: "Allows the user access to the Sheep version command."
    default: op


