name: Sheep
main: KnownUnown\Sheep\Sheep
version: 4.0.3
api: 1.0.0

author: KnownUnown
description: A plugin for managing (installing, uninstalling, searching for, etc) other plugins.
website: https://www.github.com/KnownUnown/Sheep

permissions:
  sheep.command.base:
    description: "Allows the user access to the base Sheep command, but not necessarily the subcommands."
    default: false


